# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
language: python
git:
  depth: false
env:
  - PRE_COMMIT_HOME=$HOME/.cache/pre-commit
virtualenv:
  system_site_packages: false
jobs:
  fast_finish: true
  include:
    - python: 3.7
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py37" COVERAGE="true"
    - python: 3.8
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py38" COVERAGE="false"
    - env: DISTRIB="conda" PYTHON_VERSION="3.8" COVERAGE="false"
install:
  - source tests/travis_install.sh
script:
  - tox -e build
  - tox
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
    - $HOME/.cache/pre-commit